config/routes.rb
Rails.application.routes.draw do

  root 'welcome#login'

  get 'welcome/aboutus'

  get 'welcome/legal'

  get 'welcome/support'

  resources :tasks do
    resources :replies
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
	validates :description, :datedue, presence: true
	validates :description, length: {in: 8..100}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
  class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  layout 'principal'

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.order(updated_at: :desc).limit(6)
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }

        format.js { render :create }

      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
        format.js { render :update }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
      format.js {render :destroy}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:description, :datedue, :status)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  


layout 'layouts/flash',  only: [:login]


  def login

  	
  end


  def aboutus
  end

  def legal
  end

  def support
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<div class="row footer">
	<div class="large-8 columns">
		<br>
		<h3>Una comunidad que cada día <br>tiene más usuarios solidarios</h3>
	</div>
	<div class="large-4 columns">
		<br>
		<p>Síguenos </p>
		<%= image_tag("iconos.png") %>
	</div>

</div>

app/views/layouts/_header.html.erb
<div class="row cabeza">
	<div class="large-2 columns logogente">
		<%= link_to image_tag("logo.png"), tasks_path %>
	</div>
	<div class="large-4 columns titlepage">
		<h1>Solitask</h1>
	</div>
	<div class="large-6 columns slogan">
    <h4 class="slogan">La web de la solidaridad</h4>
	</div>
</div>



 <!-- TOP BARRA NAVEGACIÓN -->

<div class="row">

<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="/">Inicio</a></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
   
    
    

    <!-- Left Nav Section -->
    <ul class="left">
      <li><a href="/welcome/aboutus">Solitask</a></li>
      <li><a href="/welcome/legal">Condiciones</a></li>
	  <li><a href="/welcome/support">Colabora</a></li>
    </ul>
  </section>
</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'vendor/modernizr', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/layouts/flash.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'vendor/modernizr', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



     

     
         
     
         
     
         
     
     <%= yield %>
         
    



  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>








</body>
</html>      

app/views/layouts/principal.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'vendor/modernizr', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render ('layouts/header') %>

<div class="row">
  <div class="large-12 columns">
     
    <div class="row">

      <div class="large-4 small-12 columns">
              <img src="https://farm5.staticflickr.com/4030/4525127157_6c0acd675c.jpg">
              <div class="hide-for-small panel">
                <h3>Usuario del mes</h3>
                <h5 class="subheader">Marco Polo ha sido el usuario que más ha contribuído a la comunidad en este mes. Congratulations!
                </h5>
              </div>
              <a href="#">
              <div class="panel callout radius">
                <h6>Tus tareas</h6>
              </div>
              </a>
      </div>
      <div class="large-8 small-12 columns">
          <%= yield %>
      </div>
    </div>
  </div>
</div>

  <%= render ('layouts/footer') %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</body>
</html>      

app/views/tasks/_form.html.erb
<script type="text/javascript">
  $(function(){
    $('#pickme').datepicker();
  });
</script>


<%= form_for(@task, remote: :true) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :datedue %><br>
    <%= f.text_field :datedue, :id => 'pickme' %>
  </div>

  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_new.html.erb
<h1>Nueva Tarea en Ajax</h1>


<%= render 'form' %>

app/views/tasks/_task.html.erb
                <div class="large-4 small-6 columns" id='task<%=task.id%>'>
                  <img src="http://loremflickr.com/200/200/people/?random=<%= rand 1..100 %>">
     
                  <div class="panel ajustepanel" >
                    <h5><%= task.description %></h5> 

                    <p><%= task.datedue %></p> 

                    <h6 class="subheader"><%= task.status  ? 'Completado' : 'Convocatoria abierta' %></h6></br>

                     
                    <%= link_to 'Mostrar', task, class: "button default tiny ourb" %>
                    <%= link_to 'Editar', edit_task_path(task), remote: :true,  class: "button default tiny ourb"  %>
                    <%= link_to 'Borrar', task, remote: :true, method: :delete, data: { confirm: '¿Seguro?' }, class: "button alert tiny ourb" %>

                  </div>
                </div>

app/views/tasks/create.js.erb
$('#tablaprincipal').prepend('<%= escape_javascript(render @task)%>')
$('#new_task').empty()
$('#task<%=@task.id%> > div').addClass('ourhighlight')

app/views/tasks/destroy.js.erb
$('#task<%=@task.id%>').remove()

app/views/tasks/edit.html.erb
<h1>Edición de tarea</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @task %> |
<%= link_to 'Atrás', tasks_path %>

app/views/tasks/edit.js.erb
$('#new_task').html('<%= escape_javascript(render 'form') %>');
$('#new_task').slideDown(1000);

app/views/tasks/index.html.erb
     

<div class="row">
  <div class="large-12 columns ourbutton">    
      <%= link_to 'Nueva Tarea', new_task_path, remote: :true, class: "button success small" %>
      <div id="new_task" style="display:none;"></div>
  </div>    
</div>
            
<div class="row" id="tablaprincipal">
     
    <% @tasks.each do |task| %>
      <%= render task%>
    <% end %>

</div>
         
<div class="row">
    <div class="large-12 columns">
                  <div class="panel">
                    <div class="row">
                      <div class="large-2 small-6 columns">
                        <img src="http://placehold.it/300x300&text=Site Owner">
                      </div>
                      <div class="large-10 small-6 columns">
                        <strong>Esta página pertenece a Solitask<hr/></strong>
                        La Fe mueve montañas.
                      </div>
                    </div>
                  </div>
     </div>
</div>
      

app/views/tasks/new.html.erb
<h1>Nueva Tarea</h1>

<%= render 'form' %>

<%= link_to 'Atrás', tasks_path %>

app/views/tasks/new.js.erb
$('#new_task').html('<%= escape_javascript(render 'new') %>');
$('#new_task').slideDown(1000);

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripción:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @task.status ? 'Completado' : 'Convocatoria abierta' %>
</p>

<%= link_to 'Editar', edit_task_path(@task) %> |
<%= link_to 'Atrás', tasks_path %>

app/views/tasks/update.js.erb
$('#task<%=@task.id%>').remove()
$('#tablaprincipal').prepend('<%= escape_javascript(render @task)%>')
$('#new_task').empty()
$('#task<%=@task.id%> > div').addClass('ourhighlight')

app/views/welcome/aboutus.html.erb
<%= render ('layouts/header')%>



<div class="row">
	<div class="large-8 columns">
		<h2>Acerca de nosotros</h2>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vestibulum, justo sit amet bibendum imperdiet, velit turpis ornare lectus, quis posuere neque nulla ut ipsum. Cras consequat elit sed pretium commodo. Vivamus semper dictum dolor, vitae pulvinar purus auctor at. Nunc ex mi, fringilla vitae posuere vel, placerat a libero. Etiam eget magna elementum, auctor velit non, dictum dui. Donec placerat quam diam, et vulputate purus convallis non. Donec sit amet pulvinar orci. Fusce auctor orci vitae sollicitudin efficitur.</p>

		<p>Mauris vitae placerat lacus. Integer nec nisl nibh. Aliquam metus felis, tempus sit amet quam vitae, accumsan aliquet leo. Donec dapibus tempor tempor. Mauris tincidunt faucibus sem sed mollis. Cras at auctor ante, a blandit mauris. Vivamus pulvinar volutpat libero, nec viverra erat pellentesque at. Donec elementum nulla ut rhoncus gravida. Ut auctor auctor diam, non pharetra ligula mattis quis.</p>

		<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In auctor dictum sapien eget volutpat. Ut mollis justo vel metus placerat tempor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In a metus justo. Nulla egestas tincidunt sapien, eu elementum erat commodo sed. Mauris a nisl id nunc vestibulum molestie quis nec dolor. Quisque at diam ac mauris congue sagittis vitae quis sem. Nam tellus diam, scelerisque id urna vel, luctus tincidunt arcu. Aenean vel sollicitudin eros.</p>

		<p>Vivamus gravida maximus libero, ac ultricies dui elementum in. Donec quis rhoncus ipsum. Etiam commodo convallis efficitur. Phasellus rutrum turpis et nunc dictum aliquam. Quisque venenatis mi et ultricies luctus. Quisque imperdiet iaculis nisl sit amet porttitor. In hac habitasse platea dictumst. Aliquam felis ante, condimentum sed viverra ut, blandit non massa. Proin eget ultrices tellus. Nam ante nisl, scelerisque sed luctus id, auctor laoreet dolor.</p>


	</div>
	<div class="large-4 show-for-large-up columns">
		<%= image_tag("arbol.jpg") %>
	</div>
</div>
<%= render ('layouts/footer')%>

app/views/welcome/legal.html.erb
<%= render ('layouts/header')%>




<div class="row">
	<div class="large-8 columns">
		<h2>Condiciones</h2>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vestibulum, justo sit amet bibendum imperdiet, velit turpis ornare lectus, quis posuere neque nulla ut ipsum. Cras consequat elit sed pretium commodo. Vivamus semper dictum dolor, vitae pulvinar purus auctor at. Nunc ex mi, fringilla vitae posuere vel, placerat a libero. Etiam eget magna elementum, auctor velit non, dictum dui. Donec placerat quam diam, et vulputate purus convallis non. Donec sit amet pulvinar orci. Fusce auctor orci vitae sollicitudin efficitur.</p>

		<p>Mauris vitae placerat lacus. Integer nec nisl nibh. Aliquam metus felis, tempus sit amet quam vitae, accumsan aliquet leo. Donec dapibus tempor tempor. Mauris tincidunt faucibus sem sed mollis. Cras at auctor ante, a blandit mauris. Vivamus pulvinar volutpat libero, nec viverra erat pellentesque at. Donec elementum nulla ut rhoncus gravida. Ut auctor auctor diam, non pharetra ligula mattis quis.</p>

		<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In auctor dictum sapien eget volutpat. Ut mollis justo vel metus placerat tempor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In a metus justo. Nulla egestas tincidunt sapien, eu elementum erat commodo sed. Mauris a nisl id nunc vestibulum molestie quis nec dolor. Quisque at diam ac mauris congue sagittis vitae quis sem. Nam tellus diam, scelerisque id urna vel, luctus tincidunt arcu. Aenean vel sollicitudin eros.</p>

		<p>Vivamus gravida maximus libero, ac ultricies dui elementum in. Donec quis rhoncus ipsum. Etiam commodo convallis efficitur. Phasellus rutrum turpis et nunc dictum aliquam. Quisque venenatis mi et ultricies luctus. Quisque imperdiet iaculis nisl sit amet porttitor. In hac habitasse platea dictumst. Aliquam felis ante, condimentum sed viverra ut, blandit non massa. Proin eget ultrices tellus. Nam ante nisl, scelerisque sed luctus id, auctor laoreet dolor.</p>


	</div>
	<div class="large-4 show-for-large-up columns">
		<%= image_tag("arbol.jpg") %>
	</div>
</div>
<%= render ('layouts/footer')%>

app/views/welcome/login.html.erb
<div class="marco">
      <div class="slick_block pic">
        <div><%= image_tag("gente.jpg") %></div>
        <div><%= image_tag("puente.jpg") %></div>
        <div><%= image_tag("punto.jpg") %></div>
      </div>
</div>









<div class="sloganfront">
      <div class="slick_block2 pic">
        <div>"La aplicación más innovadora <br>
        	que promueve la solidaridad <br>
        	nace en España". New York Times, Scott Fitzgerald</div>
        


        <div>"La aplicación que cambiará <br>
        	tu forma de ver la vida". <br>
        	 BBC, Ryan Reynols</div>
        
        <div>"Dejé el periodismo para dedicarme<br>
        	única y exclusivamente a las <br>
        	acciones solidarias". Dra. Laura Domínguez</div>
      </div>
</div>



<div class="input"> 

	<div class="caja">
		Tu nombre
	</div>




	<div class="caja">
		Tu contraseña
	</div>


	<div class="boton">
		 
		 <%= link_to 'Entrar', tasks_path %>
	</div>


</div>

app/views/welcome/support.html.erb
<%= render ('layouts/header')%>


<div class="row">
	<div class="large-8 columns">
		<h2>Colabora</h2>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vestibulum, justo sit amet bibendum imperdiet, velit turpis ornare lectus, quis posuere neque nulla ut ipsum. Cras consequat elit sed pretium commodo. Vivamus semper dictum dolor, vitae pulvinar purus auctor at. Nunc ex mi, fringilla vitae posuere vel, placerat a libero. Etiam eget magna elementum, auctor velit non, dictum dui. Donec placerat quam diam, et vulputate purus convallis non. Donec sit amet pulvinar orci. Fusce auctor orci vitae sollicitudin efficitur.</p>

		<p>Mauris vitae placerat lacus. Integer nec nisl nibh. Aliquam metus felis, tempus sit amet quam vitae, accumsan aliquet leo. Donec dapibus tempor tempor. Mauris tincidunt faucibus sem sed mollis. Cras at auctor ante, a blandit mauris. Vivamus pulvinar volutpat libero, nec viverra erat pellentesque at. Donec elementum nulla ut rhoncus gravida. Ut auctor auctor diam, non pharetra ligula mattis quis.</p>

		<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In auctor dictum sapien eget volutpat. Ut mollis justo vel metus placerat tempor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In a metus justo. Nulla egestas tincidunt sapien, eu elementum erat commodo sed. Mauris a nisl id nunc vestibulum molestie quis nec dolor. Quisque at diam ac mauris congue sagittis vitae quis sem. Nam tellus diam, scelerisque id urna vel, luctus tincidunt arcu. Aenean vel sollicitudin eros.</p>

		<p>Vivamus gravida maximus libero, ac ultricies dui elementum in. Donec quis rhoncus ipsum. Etiam commodo convallis efficitur. Phasellus rutrum turpis et nunc dictum aliquam. Quisque venenatis mi et ultricies luctus. Quisque imperdiet iaculis nisl sit amet porttitor. In hac habitasse platea dictumst. Aliquam felis ante, condimentum sed viverra ut, blandit non massa. Proin eget ultrices tellus. Nam ante nisl, scelerisque sed luctus id, auctor laoreet dolor.</p>


	</div>
	<div class="large-4 show-for-large-up columns">
		<%= image_tag("arbol.jpg") %>
	</div>
</div>
<%= render ('layouts/footer')%>